version: '3'

services:
  nginx:
    image: nginx:1.15.2
    depends_on:
      - web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/static:/static

  web:
    links:
      - db
      - redis
    depends_on:
      - db
    restart: always
    build: .
    entrypoint:
      - /config/django-entrypoint.sh
    volumes:
      - ./config:/config
      - ./src:/src
      - ./src/static:/static
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - src/online_shop/settings/.env

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./config/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - src/online_shop/settings/.env

  redis:
    image: redis:2.8.19
    hostname: redis
    ports:
     - '6379:6379'

  worker:
    links:
      - db
      - redis
    depends_on:
      - redis
    build: .
    volumes:
      - ./config:/config
      - ./src:/src
    entrypoint:
      - /config/run_celery.sh
    env_file:
      - src/online_shop/settings/.env

