# Generated by Django 2.1.4 on 2018-12-22 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('shopping_baskets', '0001_initial'), ('shopping_baskets', '0002_auto_20181221_1411'), ('shopping_baskets', '0003_auto_20181221_1426'), ('shopping_baskets', '0004_auto_20181221_2308'), ('shopping_baskets', '0005_auto_20181222_0300')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20181219_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='shopping_basket_products', to='products.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
