# Generated by Django 2.1.4 on 2018-12-21 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_baskets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='user',
        ),
        migrations.AddField(
            model_name='shoppingbasket',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
