# Generated by Django 2.1.4 on 2018-12-21 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_baskets', '0003_auto_20181221_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingbasket',
            old_name='product',
            new_name='products',
        ),
    ]
