# Generated by Django 2.1.4 on 2018-12-22 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_baskets', '0004_auto_20181221_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingbasket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
